### ISSUE TITLE
外部JSファイルの呼び出しについて

### ISSUE THREAD

**Issue by yamamoto-shunsuke** [yamamoto-shunsuke/Micropost#14]
チーム開発のissueにも記載されている、「knexのSQL文が被っている箇所のモデル化」についてご質問させていただきます。
index.jsとprofile.jsにて、フォロー、フォロワー数をknexを用いてデータベースから取得してくる一連の流れは、共通しており、モデル化できると考えたため、モデル化を試みました。モデル化するように外部ファイルを作成し、requireでその外部ファイルを読み込むように実装はできたのですが、その外部ファイルの呼び出しがうまくいっていない状態です。
hotfix/followers_following_modelingブランチに、現段階までのコードをpush致しますので、ご確認いただけないでしょうか。
また、解決につながるヒントなどお教えいただけますと幸いです。よろしくお願い致します。m(__)m

**Comment by Ivakov** [comment]
@yamamoto-shunsuke 
https://github.com/yamamoto-shunsuke/Micropost/pull/15 ですね。
確認します！

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
はい、そちらのブランチになります。
よろしくお願い致します。m(__)m

**Comment by Ivakov** [comment]
@yamamoto-shunsuke 
すみません。
2点お願いがあります。

>requireでその外部ファイルを読み込むように実装はできたのですが、その外部ファイルの呼び出しがうまくいっていない状態

について、
knexのコードをpublic/javascript直下に置いてあることは分かりましたが、それらをroutes/followers.jsやroutes/following.jsからrequireで読み込んでいる形跡が見つかりませんでした。
やってみて読み込めなかった (関数が使用できなかった) ため戻してしまったのかもしれませんが、実際に読み込もうとして問題が発生した時点のソースで確認したいです。

また、public/javascriptはフロント側の(ページに対して動的処理を行う)jsファイルを置く場所なので、プロジェクト直下のmodelsフォルダに格納してください。
(ユーザ情報を取得する関数をmodels/users.jsで実装したように)

**Comment by yamamoto-shunsuke** [comment]
`knexのコードをpublic/javascript直下に置いてあることは分かりましたが、それらをroutes/followers.jsやroutes/following.jsからrequireで読み込んでいる形跡が見つかりませんでした。`
こちらに関しまして、フォローフォロワー数をカウントし、カウントした数を表示させる処理は、トップページとプロフィールページで行っているため、index.jsファイルに記載いたしました。

`また、public/javascriptはフロント側の(ページに対して動的処理を行う)jsファイルを置く場所なので、プロジェクト直下のmodelsフォルダに格納してください。
(ユーザ情報を取得する関数をmodels/users.jsで実装したように)`
承知いたしました。まずは、現時点でのソースをご確認いただき、確認が終了次第、ファイル構成なども併せてまとめて修正いたします。

**Comment by Ivakov** [comment]
@yamamoto-shunsuke 
すみません。index.jsでしたね。
index.js確認します。

**Comment by Ivakov** [comment]
@yamamoto-shunsuke 
口頭で伝えましたが、こちらにも書いておきます。

まず、どちらの関数もreturnしていません。
knexでデータベース操作を行うだけで結果を返さない関数になっているので、
index.js側で何も実行結果を取得できず、読み込めていないように"みえている"だけです。

また、`module.exports = function (followed_id,req,res) {}` としているのですが、
`req.user.id` とするためだけにindex.jsから `req` オブジェクトを受け取るのは大きすぎるので、
index.js側で `const userId = req.user.id;` などとしてそれを受け取る方が良いです。
 `res` オブジェクトはこの関数内で何も使うところがないので消してください。

また、1ファイル1関数としていますが、今回の場合、フォロー・フォロワーを1つのカテゴリとして、
例えばmodels/relationship.jsを作成して、その中にフォロー・フォロワーに使う関数を実装した方がすっきりすると思います。
