### ISSUE TITLE
ログイン認証後,req.userオブジェクトから値取得時にundefinedとなることについて

### ISSUE THREAD

**Issue by yamamoto-shunsuke** [yamamoto-shunsuke/Micropost#5]

**Comment by yamamoto-shunsuke** [comment]
表題の件について、ご質問がございます。
前提として、昨日、12月16日に実施したチーム開発にて、app.jsに記述していたルーティング処理をindex.jsに記述することやパスポート機能をモデル化するなど、チーム開発で修正した部分は最終課題の方にも反映を行いました。
ログイン認証についてですが、ログイン成功後にログ出力でreq.userオブジェクトから値の取得ができるか試しましたが、「undefined」となってしまい、値を取得することができませんでした。
また、isAuthenticatedメソッドにつきましては、ログイン後に「false」から「true」になったことを確認しております。
以下のサイトを参考にエラー解消できるか試行錯誤しましたが、エラーを解消することができませんでした。
https://stackoverflow.com/questions/16434893/node-express-passport-req-user-undefined
https://knimon-software.github.io/www.passportjs.org/guide/login/
お手数ですが、ご教授願います。
※こちらの修正は、現在上がっているfeature/login_after_top_pageブランチで行っております。

**Comment by Ivakov** [comment]
@yamamoto-shunsuke 

遅くなってすみません。コード確認しました。
チーム開発のときに漏れていたものもいくつかありました (すみません。。)

まず、deserializeUser内の `const user = User.findById(id);` の下に、`console.log(user);` を追加してログを確認すると分かるのですが、Promise { \<pending\> }となっています。

これを解決するために2点修正が必要です。

1. passport.jsのdeserializeUser内の処理にasync awaitを適用する

```
passport.deserializeUser(async function (id, done) {
  try {
    const user = await User.findById(id);
    done(null, user);
  } catch (error) {
    done(error, null);
  }
});
``` 

2. user.jsのfindByIdの処理を二段階に分ける (async functionを2つにする)。

```
const TABLE_NAME = "users";

async function findById(userId) {
  const user = await where({id: userId});
  if (user === null) {
    throw new Error("User not found")
  }

  return {...user};
}

async function where(condition) {
  return await knex(TABLE_NAME)
    .where(condition)
    .then((results) => {
      if (results.length === 0) {
        return null;
      }
      return results[0];
    });
}
```

また、山本さんのコードでいくつかおかしい点がありました (上記のサンプルコードはその修正も込みです)。

- usersテーブルの全件を取得している (userIdを条件とした.whereを使用していない)
  findById(userId)で引数としてユーザIDを受け取っていながら、userIdでの絞り込みを行っていません。
  そもそもdeserializeUserはリクエストがあったユーザの情報をreq.userに格納するためのミドルウェアなので、今のままでは全ユーザの情報を格納してしまいます。

- ユーザidのみ返している (`return rows[0].id`)
  req.userに格納したいのはユーザidだけではないはずです (ユーザ名等もreq.userに格納したい)。

以下上記のサンプルコードの補足です。

- conditionについて
conditionは様々な条件に対応できるようにするために引数としています。
今回であれば{id: userId}の条件なので、`const user = await where({id: userId});`でwhere関数を呼び出す際にその条件を引数に与えています。

- TABLE_NAMEについて
TABLE_NAMEは後にuser.js内でuserテーブルを操作する別の関数を実装する際に便利なので、
`const TABLE_NAME = "users";` で定数化しています。

- `return {...user};` の`{...user}`について
まず `user`は `const user = await where({id: userId});` の `user` なので、つまり`await where({id: userId});` の返り値 (`results[0];`) ですが、`result[0]` とすると以下のようにRowDataPacketオブジェクトになります(これはデフォルトなので何も手を加えなければこうなります)。

```
RowDataPacket {
  id: 1,
  name: 'admin',
  email: 'admin@example.com',
  password: '$2b$10$nUQq20YY6laWt0sp3zgDBehkXd6rnNdXIM8rWUaZzfxK6pg4oy0G6',
  isAdmin: 1,
  reset_token: null,
  reset_limit: null,
  activation_token: null,
  isActivated: 1,
  activated_at: 2020-11-25T08:35:08.000Z,
  created_at: null,
  updated_at: null
}
```

RowDataPacketオブジェクトのままでもreq.userに格納する上で問題ないのですが、`{...user}` とすることで、RowDataPacketを除去することができます。
...はスプレッド構文というものです(https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Spread_syntax)。
...を付けることでオブジェクトの{}を取り除くことができます。

また、以下のように2つのオブジェクトをマージするときなどにも利用します。
```
let obj1 = { foo: 'bar', x: 42 };
let obj2 = { foo: 'baz', y: 13 };

let mergedObj = { ...obj1, ...obj2 };
// Object { foo: "baz", x: 42, y: 13 }
```

おそらくこれらの修正で動くようになるはずです。
もし、passportで今回のように動かない等の動作に関する質問以外で、何か質問があれば今週水曜に口頭でいただきたいです。口頭の方が伝えやすいので。

よろしくお願いします。

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
ご回答ありがとうございます。
まとめてご確認いたします。passport機能の動作に関して、また疑問点等出てきましたら再度ご質問させていただきます。

`もし、passportで今回のように動かない等の動作に関する質問以外で、何か質問があれば今週水曜に口頭でいただきたいです。口頭の方が伝えやすいので。`

上記についても承知いたしました！
